[package]
name = "fount"
version = "0.1.0"
authors = ["Chad Brokaw <cbrokaw@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
memmap2 = "0.5.3"
swash = { git = "https://github.com/dfrg/swash" }